### ISSUE TITLE
error... Please share how to pass arguments

### ISSUE THREAD

**Issue by itsinsightful** [kjanko/python-fingerprint-recognition#20]
Traceback (most recent call last):
  File "app.py", line 111, in <module>
    main()
  File "app.py", line 76, in main
    kp1, des1 = get_descriptors(img1)
  File "app.py", line 45, in get_descriptors
    img = image_enhance.image_enhance(img)
  File "C:\Users\Pavilion\Downloads\python-fingerprint-recognition-master\python-fingerprint-recognition-master\enhance\image_enhance.py", line 15, in image_enhance
    normim,mask = ridge_segment(img,blksze,thresh);             # normalise the image and find a ROI
  File "C:\Users\Pavilion\Downloads\python-fingerprint-recognition-master\python-fingerprint-recognition-master\enhance\ridge_segment.py", line 61, in ridge_segment
    rows,cols = im.shape;
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by itsinsightful** [comment]
Please reply
