### ISSUE TITLE
Unable to resolve this please help

### ISSUE THREAD

**Issue by itsinsightful** [kjanko/python-fingerprint-recognition#21]
File "app.py", line 45, in get_descriptors
    img = image_enhance.image_enhance(img)
  File "C:\Users\Pavilion\Downloads\python-fingerprint-recognition-master\python-fingerprint-recognition-master\enhance\image_enhance.py", line 35,
 in image_enhance
    newim = ridge_filter(normim, orientim, freq, kx, ky);       # create gabor filter and do the actual filtering
  File "C:\Users\Pavilion\Downloads\python-fingerprint-recognition-master\python-fingerprint-recognition-master\enhance\ridge_filter.py", line 83,
in ridge_filter
    x,y = np.meshgrid(np.linspace(-sze,sze,(2*sze + 1)),np.linspace(-sze,sze,(2*sze + 1)));
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\Users\Pavilion\PycharmProjects\office\venv\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by itsinsightful** [comment]
@kjanko  @ogabriel  ..Please Help

**Comment by loreloc** [comment]
Hi, i think this is due to a numpy documentation misleading. Numpy's round function doesn't cast to int.
Try replacing the previous line with this.
`sze = np.round(3*np.max([sigmax,sigmay])).astype('int');`

**Comment by codulers** [comment]
@loreloc Thanks for suggestion

Its Resolved .

**Comment by adrianodisam** [comment]
Traceback (most recent call last):
  File "C:/Users/adria/Desktop/python-fingerprint-recognition-master/python-fingerprint-recognition-master/app.py", line 9, in <module>
    os.chdir("/app.py")
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado: '/app.py'

**Comment by mukheshpugal** [comment]
@adrianodisam comment that line out

**Comment by justShae** [comment]
"C:\Users\akank\PycharmProjects\new file\.venv\Scripts\python.exe" "C:\Users\akank\PycharmProjects\new file\app.py" 
Traceback (most recent call last):
  File "C:\Users\akank\PycharmProjects\new file\app.py", line 111, in <module>
    main()
  File "C:\Users\akank\PycharmProjects\new file\app.py", line 74, in main
    image_name = sys.argv[1]
                 ~~~~~~~~^^^
IndexError: list index out of range

Process finished with exit code 1




please help!!!!!!!!!!!!!!!!!!!!!!!!!!
